[package]
name = "on-air-warning-windows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1"
tray-item = "0.7.1"

[build-dependencies]
windres = "*"
